### ISSUE TITLE
Pass Image URI instead on string parameters

### ISSUE THREAD

**Issue by veris-amoghbanta** [ahmadms1/react-native-brptouchprinter#1]
Hi,
Can you please help me guiding on how to pass an image/PDF URI from JS side on bridge and print that using this library. I don't have experience in objective-C but can understand the basic stuff.
Would really appreciate it.
Thanks

**Comment by ahmadms1** [comment]
Hi @veris-amoghbanta, 

I'm really sorry but this repo was intended for a side project I was working on and the objective was to print out some strings on a label using the Brother P-touch printer. Plus, the code only works specifically for label printer QL-720NW. You might need to change the objective-C code to make it work with any other printer supported by Brother Printer SDK.

If you want to print an image/PDF, you will need to go through the Brother P-touch printer SDK manuals. The documentation contains example on how you can do that using the printers they supported. 

I too didn't have experience in objective-C like you when I created this repo. But if you go through the manual they provided, it is really easy to understand. :+1:

**Comment by veris-amoghbanta** [comment]
I am also using QL-720NW. I'll go through the manuals. Thanks 👍
